Game/urls.py
from django.urls import path
from .views import antigod_mode, gode_mode, greet, new_game, shop, start_page, stat_update,travel,fight, new_game_page, \
    rest, equip, eat, new_game, travel_page, finish_game, show_hint
app_name='Game'
urlpatterns=[
    path('', start_page, name='start_page'),
    path('greet/', greet, name='greetings'),
    path('travel/', travel, name='travel'),
    path('travel_page/', travel_page, name='travel_page'),
    path('fight/', fight, name='fight'),
    path('shop/<str:place>/', shop, name='shop'),
    path('rest/', rest, name='rest'),
    path('equip/', equip, name='equip'),
    path('stat_update/', stat_update, name='stat_update'),
    path('eat/', eat, name='eat'),
    path('show_hint/', show_hint, name='show_hint'),
    path('finish/', finish_game, name='finish_game'),
    path('new_game_page/', new_game_page, name='new_game_page'),
    path('new_game/', new_game, name='new_game'),
    path('god_mode/', gode_mode, name='god_mode'),
    path('antigod_mode/', antigod_mode, name='antigod_mode'),
]

Winterhold/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Game.urls')),
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path
from django.urls.conf import include
from .views import register
app_name='user'
urlpatterns=[
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='registration')
]

Game/models.py
from multiprocessing import Condition
from random import choices
from statistics import mode
from django.db import models
from django.db.models.deletion import PROTECT
from django.forms import IntegerField, Textarea

# Create your models here.

class Enemy(models.Model):
    name=models.CharField(max_length=21)
    damage=models.IntegerField()
    hp=models.IntegerField(null=True)
    alive=models.BooleanField(default=True)
    reward=models.IntegerField(null=True)
    exp = models.IntegerField(default=0)
    msg=models.TextField()
    seal=models.CharField(max_length=30, blank=True)
    death_message=models.TextField(null=True)

    def __str__(self) -> str:
        return self.name

class Place(models.Model):
    x=models.IntegerField(blank=False)
    y=models.IntegerField(blank=False)
    subloc_pk = models.IntegerField(default=0)
    name=models.CharField(max_length=20)
    msg=models.TextField()
    enemy=models.ForeignKey(Enemy, on_delete=PROTECT, blank=True, null=True)
    not_allowed_direction=models.CharField(max_length=100, blank=True)
    transition = models.BooleanField(default = False)
    is_shop=models.BooleanField(default=False)
    is_rest_place=models.BooleanField(default=True)
    is_first_enter=models.BooleanField(default=True)
    first_enter_text=models.TextField(blank=True)

    def __str__(self) -> str:
        return self.name

class Armor(models.Model):
    parts=[
        ('helmet','Шлем'),
        ('chestplate','Нагрудник'),
        ('leggings','Поножи'),
        ('boots','Ботинки')
    ]

    name=models.CharField(max_length=40)
    price=models.IntegerField()
    protection=models.IntegerField()
    level = models.IntegerField(default = 1)
    section=models.CharField(max_length=30, default='Armor')
    part=models.CharField(choices=parts,max_length=30,blank=True)
    dexterity=models.IntegerField(default = 0)

    def __str__(self):
        return self.name

class Weapon(models.Model):
    name=models.CharField(max_length=40)
    price=models.IntegerField()
    damage=models.IntegerField()
    level = models.IntegerField(default = 1)
    section=models.CharField(max_length=30, default='Weapon')
    crit_add=models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Food(models.Model):
    name=models.CharField(max_length=50)
    price=models.IntegerField()
    satiety=models.IntegerField()
    section=models.CharField(max_length=50, default='Food')

    def __str__(self):
        return self.name

class Hint(models.Model):
    text=models.TextField()

    def __str__(self):
        return ' '.join(self.text.split()[:5])

Game/views.py
from math import radians
import re
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required
from django.http.response import Http404
from django.shortcuts import redirect, render

import shelve
from random import choice, randint
from icecream import ic

from Game.models import Enemy, Food, Hint, Place, Armor, Weapon
from .game_classes import Character, antigod_mode_stats, buy, change_place, eat_food, god_mode_stats, roll, pack, unpack,  \
    atack, dodge, check, equip_item, check_enemy, update_stat
from Winterhold.settings import STAT_TRANSLATION

#Views 
def start_page(request:HttpRequest):
    if request.user.is_authenticated:
        return redirect("Game:travel")
    return render(request, 'Game/start_page.html')
 
@login_required
def new_game_page(request):
    return render(request, 'Game/new_game.html')

@login_required
def new_game(request):
    user=str(request.user.pk)
    pack(user, 'ch', Character())
    return redirect('Game:greetings')

@login_required
def greet(request):
    user=str(request.user.pk)
    if user in shelve.open(f'ch_files/{user}').keys():
        return redirect("Game:travel")
    else:
        pack(user, 'ch', Character())
    
    return render(request, 'Game/greetings.html', context={"ch":unpack(str(request.user.pk), 'ch')})

@login_required
def travel(request:HttpRequest):
    
    user=str(request.user.pk)
    ch=unpack(user, 'ch')
     
    msg=ch.place.msg

    if request.method == 'POST':
            
        msg, coords_changed=change_place(request, ch)

        if ch.place.is_first_enter and coords_changed and not ch.is_god:
            pack(user, 'ch', ch)
            return redirect('Game:travel_page')

    if check_enemy(ch):
        pack(user, 'ch', ch)
        return redirect("Game:fight")
    
    pack(user, 'ch', ch)
    context={'ch':ch, 'msg':msg}
    return render(request, 'Game/travel.html', context)

@login_required
def travel_page(request:HttpRequest):
    user=str(request.user.pk)
    ch=unpack(user, 'ch')
    
    ch.place.is_first_enter=False
    
    pack(user, 'ch', ch)
    context={'ch':ch}
    return render(request, 'Game/travel_page.html', context)

@login_required
def fight(request):
    user=str(request.user.pk)
    ch=unpack(user, 'ch')

    if not ch.enemy:
        return redirect("Game:travel")

    atack_msg=atack(request, ch)

    if atack_msg=='run':
        pack(user, 'ch', ch)
        return redirect("Game:travel")

    dodge_msg=dodge(request, ch)

    pack(user, 'ch', ch)
    return render(request, *check(user, ch, atack_msg, dodge_msg))


@login_required
def shop(request:HttpRequest, place):
    user=str(request.user.pk)
    ch=unpack(user, 'ch')
    msg=''
    
    if ch.place.name!=place:
        raise Http404
        
    if request.method=='POST':
        msg=buy(request, ch)
    else:
        msg='Добро пожаловать'

    if place=='Кузня':
        goods=list(Armor.objects.exclude(name__in=ch.inventory).order_by('price')) + list(Weapon.objects.exclude(name__in=ch.inventory).order_by('price'))
    elif place=='Таверна':
        goods=Food.objects.all()

    pack(user, 'ch', ch)
    context={'goods':goods, 'ch':ch, 'msg':msg}
    return render(request, 'Game/shop.html', context)

@login_required
def rest(request:HttpRequest):
    user=str(request.user.pk)
    ch=unpack(user, 'ch')

    if check_enemy(ch):
        raise Http404

    return render(request, 'Game/rest.html', {'ch':ch})
    
@login_required
def equip(request:HttpRequest):
    user=str(request.user.pk)
    ch=unpack(user, 'ch')

    if check_enemy(ch):
        raise Http404

    msg=''
    if request.method=='POST':
        msg=equip_item(request, ch)
    
    inventory=list(filter(lambda item:item.section in ('Armor', 'Weapon') and item not in (ch.weapon, ch.helmet, ch.chestplate, ch.leggings, ch.boots), ch.inventory))
    context={'inventory':inventory, 'msg':msg, 'ch':ch}
    pack(user, 'ch', ch)
    return render(request, 'Game/equipment.html', context)

@login_required
def stat_update(request:HttpRequest):
    user = str(request.user.pk)
    ch = unpack(user, 'ch')
    
    if check_enemy(ch):
        raise Http404

    msg = 'Что желаете улучшить?'
    
    if request.method == 'POST':
        msg = update_stat(ch, request.POST['update'])
    
    pack(user, 'ch', ch)
    context = {'point_translation':STAT_TRANSLATION, 'ch':ch, 'msg':msg}
    return render(request, 'Game/stat_update.html', context)

@login_required
def eat(request:HttpRequest):
    user=str(request.user.pk)
    ch=unpack(user, 'ch')

    if check_enemy(ch):
        raise Http404

    if request.method=='POST':
        eat_food(request.POST['eat'], ch)

    food = {f.name:ch.inventory.count(f) for f in set(filter(lambda item: item.section=='Food', ch.inventory))}
    context={'food':food, 'ch':ch}

    pack(user, 'ch', ch)
    return render(request, 'Game/eat.html', context)

@login_required
def show_hint(request:HttpRequest):
    user=str(request.user.pk)
    ch=unpack(user, 'ch')

    if ch.place.name!='Таверна':
        raise Http404

    hints=Hint.objects.exclude(pk__in=ch.hints)

    if not hints:
        text='Мне больше нечего тебе сказать, странник'
    else:
        hint=hints[randint(0, len(hints)-1)]
        text=hint.text
        ch.hints.append(hint.pk)

    pack(user, 'ch', ch)
    context={'hint':text, 'ch':ch}
    return render(request, 'Game/hint.html', context)

@login_required
def finish_game(request:HttpRequest):
    ch=unpack(str(request.user.pk), 'ch')

    if ch.map['Руины'].enemy.alive:
        raise Http404
    
    return render(request, 'Game/finish_game.html')

@login_required
def gode_mode(request:HttpRequest):
    user=str(request.user.pk)

    if not request.user.is_superuser:
        raise Http404
    
    ch=unpack(user, 'ch')
    god_mode_stats(ch)
    pack(user, 'ch', ch)
    return redirect("Game:travel")

@login_required
def antigod_mode(request:HttpRequest):
    user=str(request.user.pk)

    if not request.user.is_superuser:
        raise Http404

    ch=unpack(user, 'ch')
    antigod_mode_stats(ch)
    pack(user, 'ch', ch)
    return redirect("Game:travel")

templates/Game/eat.html
{% extends 'Layout/basic.html' %}
{% block title %}Eat{% endblock %}
{% block content %}
    <form id='eat_form' action="" method="post">
        {% csrf_token %}
        <input type="hidden" value="" name='eat' id='eat'>
    </form>
    {% for f, q in food.items %}
        <p>{{f}}:{{q}}</p>
        <button id='food'
            onclick="document.getElementById('eat_form').elements.eat.value='{{f}}'; document.getElementById('eat_form').submit();">Съесть</button>
    {% empty %}
        <p>У вас нет еды в инвентаре</p>
    {% endfor %}
    <form action="{% url 'Game:rest' %}">
        <button>Назад</button>
    </form>
{% endblock %}

templates/Game/equipment.html
{% extends 'Layout/basic.html' %}
{% block title %}Equip{% endblock %}
{% block content %}
    <h2>{{msg}}</h2>
    <form id='equipment_form' action="" method="post">
        {% csrf_token %}
        <input type='hidden' value="" name='equipment' id='equipment'>
    </form>
    <div class="panel">
    {% for item in inventory %}
        <div class="goods" style="height: 150px" >
            <p>{{item}}</p>
            <p>Нужный уровень: {{item.level}}</p>
            <button id='equip'
                onclick="document.getElementById('equipment_form').elements.equipment.value='{{item}},{{item.section}}'; document.getElementById('equipment_form').submit();">Экипировать</button>
        </div>
    {% empty %}
        <p class="empty">*Звук сверчков*</p>
    {% endfor %}
</div>
    <form action="{% url 'Game:rest' %}">
        <button>Назад</button>
    </form>
{% endblock %}

templates/Game/fight.html
{% extends 'Layout/basic.html' %}
{% block title %}Файтинг{%endblock%}
{% block content %}
    <h2>{{enemy.name}}</h2>
    <p>{{enemy.hp}}/{{enemy_max_hp}}</p>
    <p>{{atack_msg}}</p>
    <p>{{dodge_msg}}</p>

    <form id='atack_form' action="" method="post">
        {%csrf_token%}
        <input type='hidden' value="" name='atack' id='atack'>
    </form>

    <button id='head'
        onclick="document.getElementById('atack_form').elements.atack.value = 'head'; document.getElementById('atack_form').submit();">Голова</button>
    <button id='body'
        onclick="document.getElementById('atack_form').elements.atack.value = 'body'; document.getElementById('atack_form').submit();">Корпус</button>
    <button id='limbs'
        onclick="document.getElementById('atack_form').elements.atack.value = 'limbs'; document.getElementById('atack_form').submit();">Конечности</button>
    <button id='run'
        onclick="document.getElementById('atack_form').elements.atack.value = 'run'; document.getElementById('atack_form').submit();">Бежать</button>
{% endblock %}

templates/Game/finish_game.html
{% extends 'Layout/basic.html' %}
{% block title %}Goodbye!{% endblock %}
{% block content %}
    <p>
        Вы выполнили свое задание, принцесса благодарна и сполна отплатила вам. 
        Но, похоже ее возлюбленный пропал и она просит найти его. 
        Вы с горечью понимаете, что натворили...
    </p>
    
    <form action="{% url 'Game:travel' %}">
        <button>Вернуться</button>
    </form>
{% endblock %}

templates/Game/greetings.html
{% extends 'Layout/basic.html' %}
{%block title %}Greetings{%endblock%}
{% block content %}
    <div class="home">
    
        <p class="text_board">
            Ваша история начинается в одном из великих замков материка, Винтерхолде.<br>
            <br>
            В этот день вас вызвала к себе принцесса Анна и поручила особо важную миссию.
            Вам необходимо будет встретится лицом к лицу с одним из богов этого мира.
            Принцесса рассказала вам, что ее родители собираются вступить в сговор со тьмой.
            Ваша миссия заключается в предотвращении данной сделки.
            Единственное, что известно, это то, что бог скрывается в руинах, закрытыми 4 печатями.
            Принцесса желает вам удачи в пути.
        </p>

    <div class="col center">
        <a href="{% url 'Game:travel' %}" class="btn btn-sm animated-button victoria-one">Start game</a>
    </div>

    </div>
{%endblock%}

templates/Game/hint.html
{% extends 'Layout/basic.html' %}
{% block title %}Hint{% endblock %}
{% block content %}
    <h1>Здравствуй, странник</h1>
    <p>{{hint}}</p>
    {% if hint != 'Мне больше нечего тебе сказать, странник' %}
        <form action="">
            <button>Попросить еще подсказку</button>
        </form>
    {% endif %}
    <form action="{% url 'Game:travel' %}">
        <button>Вернуться</button>
    </form>
{% endblock %} 

templates/Game/lose.html
{% extends 'Layout/basic.html'%}
{% block title %}Lose{% endblock %}
{% block content %}
    <h2>Вы проиграли</h2>
    <p>{{msg}}</p>
    <form action='{% url "Game:travel" %}'>
        <button>Продолжить</button>
    </form>
{% endblock %}

templates/Game/new_game.html
{% extends 'Layout/basic.html' %}
{% block title %}New game{%endblock%}
{% block content %}
    <p>Вы уверены, что хотите начать все заново?</p><br />
    <a href='{% url "Game:new_game" %}'>Да</a><br />
    <a href='{% url "Game:travel" %}'>Вернуться</a>
{% endblock %}

    

templates/Game/rest.html
{% extends 'Layout/basic.html' %}
{% block title %}Rest{% endblock %}
{% block content %}
    <p>Вы находите удобное место в тени</p>

    <form action="{% url 'Game:equip' %}">
        <button>Рюкзак</button>
    </form>

    <form action="{% url 'Game:eat' %}">
        <button>Перекусить</button>
    </form>

    <form action = "{% url 'Game:stat_update' %}">
        <button>Улучшить навык</button>
    </form>

    <form action="{% url 'Game:travel' %}">
        <button>Вернуться</button>
    </form>
    
{% endblock %}

templates/Game/shop.html
{% extends 'Layout/basic.html'%}
{% block title %}Shop{% endblock %}
{% block content %}
     <!--Самый тяжелый для тебя шаблон, веселья там-->
     <h1>Здравствуй, странник</h1>
     <h2>{{msg}}</h2>

     <form id='shop_form' action="" method="post">
          {%csrf_token%}
          <input type='hidden' value="" name='buy' id='buy'>
     </form>
<div class="panel">
    {% for good in goods %}
    <div class="goods">
          <p>{{good.name}}</p>
          <p>Цена:{{good.price}}</p>
          <!--В Кузне было бы неплохо разделить оружие и броню; я могу отсортировать элементы в цикле-->
          {% if good.section == "Weapon" %}
               <p>Урон: {{good.damage}}</p>
               <p>Нужный уровень: {{good.level}}</p>
          {% elif good.section == "Armor" %}
               <p>Защита: {{good.protection}}</p>
               <p>Нужный уровень: {{good.level}}</p>
          {% elif good.section == "Food" %}
               <p>Сытость: {{good.satiety}}</p>
          {% endif %}
                  
          <button id='{{good.name}}' 
               onclick="document.getElementById('shop_form').elements.buy.value='{{good}},{{good.section}}'; document.getElementById('shop_form').submit();">Купить</button>
        </div>
     {% empty %}
        <p class="empty">Кажись, мне нечего тебе предложить</p>
    {% endfor %}
</div>
     <!--Вот это аккуратненько перенеси куда нибудь-->
     {% if ch.place.name == 'Таверна' %}
          <form action="{% url 'Game:show_hint' %}">
               <button>Попросить подсказку</button>
          </form>
     {% endif %}

     <form action="{% url 'Game:travel' %}">
          <button>Вернуться</button>
     </form>
{% endblock %}

templates/Game/start_page.html
{% extends 'Layout/basic.html' %}
{% block title %}Start{%endblock%}
{% block content %}
    <!--Веселая херотень-->
    <!--Здесь не нужно что бы отображались статы из basic-->
    <h1>Добро пожаловать в Winterhold</h1>
    <a href='{% url "user:login" %}'>Войти</a>
    <p>Еще не были на материке? Тогда вам сюда:</p>
    <a href='{% url "user:registration" %}'>Зарегистрироваться</a>
{% endblock %}

templates/Game/stat_update.html
{% extends 'Layout/basic.html' %} 
{% block title %}Update{% endblock %}
{% block content %} 
    <form id='skill_form' action="" method="post">
        {% csrf_token %}
        <input type="hidden" value="" name='update' id='update'>
    </form>
    {% for stat, value in ch.allocated_points.items %}
        <p>{{stat}} - {{value}}</p>
    {% endfor %}
    <h2>Текущее количество очков: {{ch.lvl_points}}</h2>
    <p>{{msg}}</p>
    {% for stat, translate in point_translation.items %}
        <p>{{translate}}</p>
        <button id='{{stat}}' onclick="document.getElementById('skill_form').elements.update.value = '{{stat}}'; document.getElementById('skill_form').submit();">Улучшить</button>
    {% endfor %}
    <form action="{% url 'Game:travel' %}">
        <button>Вернуться</button>
    </form>

{% endblock %}

templates/Game/travel.html
{% extends 'Layout/basic.html' %}
{% load static %}
{% block title %}Главная{%endblock%}
{% block content %}
    <h1>Текущая локация: {{ch.place.name}}</h1>
    <h2>x:{{ch.x}}, y:{{ch.y}}, z:{{ch.sublocation_pk}}</h2>
    <p>{{msg}}</p>
    <form id='direction_form' action="" method="post">
        {%csrf_token%}
        <input type='hidden' value="" name='direction' id='direction'>
    </form>

    <div class="block_c">
        <button class="buttom_c" id='a'
            onclick="document.getElementById('direction_form').elements.direction.value = 'a'; document.getElementById('direction_form').submit();">
            <img style="transform: rotate(-90deg);" src="{% static 'Game/picture/buttom.png' %}"></button>
                <div class="row">
                    <button class="buttom_c" id='w'
                        onclick="document.getElementById('direction_form').elements.direction.value = 'w'; document.getElementById('direction_form').submit();">
                        <img src="{% static 'Game/picture/buttom.png' %}"></button>
                    <button class="buttom_c" id='s'
                        onclick="document.getElementById('direction_form').elements.direction.value = 's'; document.getElementById('direction_form').submit();">
                        <img style="transform: rotate(180deg);" src="{% static 'Game/picture/buttom2.png' %}"></button>
                </div>
        <button class="buttom_c" id='d'
            onclick="document.getElementById('direction_form').elements.direction.value = 'd'; document.getElementById('direction_form').submit();">
            <img style="transform: rotate(90deg);" src="{% static 'Game/picture/buttom2.png' %}"></button>
    </div>

    {% if ch.place.transition %}
        <button id = 'go_into'
            onclick="document.getElementById('direction_form').elements.direction.value = 'go_into'; document.getElementById('direction_form').submit();">Перейти</button>
    {% endif %}

    {% if ch.place.is_shop %}
        <form action="{% url 'Game:shop' ch.place.name %}">
            <button>Зайти</button>
        </form>
    {% endif %}
    
    {% if ch.place.is_rest_place %}
        <form action='{% url "Game:rest" %}'>
            <button>Сделать привал</button>
        </form>
    {% endif %}
    
{% endblock %}

templates/Game/travel_page.html
{% extends 'Layout/basic.html' %}
{% block title %}Travel page{% endblock %}
{% block content %}
    <p>{{ch.place.first_enter_text}}</p>
    <form action="{% url 'Game:travel' %}">
        <button>Дальше</button>
    </form>
{% endblock %}